version: "3.1"
services:
  usersapp:
    container_name: springusers
    image: springusers
    build: users-service/
    ports:
      - "8081:8081"
    depends_on:
      - db
      - departementapp
  departementapp:
    container_name: springdepartement
    image: springdepartement
    build: departement-service/
    ports:
      - "8082:8082"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dadinos
      - POSTGRES_DATABASE=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/

volumes:
  db-data