version: "3.1"
services:
  usersapp:
    container_name: springusers
    image: springusers
    build: users-service/
    ports:
      - "8082:8082"
    depends_on:
      - db
      - departementapp
      - registryapp
  departementapp:
    container_name: springdepartement
    image: springdepartement
    build: departement-service/
    ports:
      - "8081:8081"
    depends_on:
      - db
      - registryapp
  registryapp:
    container_name: springregistry
    image: springregistry
    build: service-registry/
    ports:
      - "8761:8761"
  db:
    container_name: db
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dadinos
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/

volumes:
  db-data: